from dataclasses import dataclass
@dataclass
class Steps:
    def __init__(self):
        self.steps = []
    
    def inputs(self):
        """
        Returns input keywords used in the processing steps.
        """
        keywords = set()
        for step in self.steps:
            if 'keyword1' in step and step['keyword1']:
                keywords.add(step['keyword1'])
            if 'keyword2' in step and step['keyword2']:
                keywords.add(step['keyword2'])
        return list(keywords)
    
    def outputs(self):
        """
        Returns output keys generated by the processing steps.
        """
        outputs = set()
        for step in self.steps:
            if 'output_key' in step and step['output_key']:
                outputs.add(step['output_key'])
        return list(outputs)
    
    def last_used(self):
        """
        For each input keyword, Determine, at what step number when input keyword is last used and put it in dictionary
        """
        
        input_keywords = self.inputs()
        input_order = dict()
        
        # Initialize all output keywords with -1 to indicate they are not used in any step
        for keyword in self.outputs():
            input_order[keyword] = -1

        # Iterate through steps and update last used index for each input keyword
        for keyword in input_keywords:
            for idx, step in enumerate(self.steps):
                if step.get('keyword1') == keyword or step.get('keyword2') == keyword:
                    input_order[keyword] = idx
        
        return input_order
    
    def set_steps(self, steps):
        """
        Sets cleaned processing steps.
        """
        self.steps = steps

    def get_steps(self):
        """
        Returns:
        List of processing steps.
        """
        return self.steps