from dataclasses import dataclass
import logging
from typing import Any

logger = logging.getLogger(__name__)

@dataclass
class Steps:
    def __init__(self) -> None:
        self.steps: list[dict[str, Any]] = []
    
    def inputs(self, include_computed: bool = True) -> list[str]:
        """Return input keywords used in configured processing steps.

        Args:
            include_computed: Whether to include keywords that are generated by
                previous processing steps.

        Returns:
            List of unique input keywords.
        """
        keywords: set[str] = set()
        for step in self.steps:
            if 'keyword1' in step and step['keyword1']:
                keywords.add(step['keyword1'])
            if 'keyword2' in step and step['keyword2']:
                keywords.add(step['keyword2'])
        if not include_computed:
            for keyword in self.outputs():
                keywords.discard(keyword)
        return list(keywords)
    
    def outputs(self) -> list[str]:
        """Return output keys generated by configured processing steps."""
        outputs: set[str] = set()
        for step in self.steps:
            if 'output_key' in step and step['output_key']:
                outputs.add(step['output_key'])
        return list(outputs)
    
    def last_used(self) -> dict[str, int]:
        """Return the last step index where each keyword is referenced."""
        
        input_keywords = self.inputs()
        input_order: dict[str, int] = dict()
        
        # Initialize all output keywords with -1 to indicate they are not used in any step
        for keyword in self.outputs():
            input_order[keyword] = -1

        # Iterate through steps and update last used index for each input keyword
        for keyword in input_keywords:
            for idx, step in enumerate(self.steps):
                if step.get('keyword1') == keyword or step.get('keyword2') == keyword:
                    input_order[keyword] = idx
        
        return input_order
    
    def set_steps(self, steps: list[dict[str, Any]]) -> None:
        """Set normalized processing steps."""
        logger.debug(f"Setting steps: {steps}")
        self.steps = steps

    def get_steps(self) -> list[dict[str, Any]]:
        """Return configured processing steps."""
        return self.steps